### ISSUE TITLE
Focus a procházení odkazů tabulátorem

### ISSUE THREAD

**Issue by pilniczek** [ridercz/Blog#16]
https://www.altair.blog/2020/01/scss-menu

Řešení v CodePen iframu ani na Codepen stránce nereaguje na procházení odkazů tabulátorem.

Nepodařilo se mi menu otevřít bez pomoci myši.

**Comment by ridercz** [comment]
Horizontální menu funguje s klávesnicí normálně. Vertikální menu je určené pro mobily a dotykové obrazovky. Tam použití klávesnice nepředpokládám a tudíž to nepovažuji za chybu.
