### ISSUE TITLE
Vláda zbabělců a fachidiotů

### ISSUE THREAD

**Issue by ookami82** [ridercz/Blog#20]
https://www.altair.blog/2020/05/fachidioti

Nalezena hrubá gramatická chyba ve druhém souvětí posledního odstavce:

> Dokud se __nezbavýme__ mýtu...

Prosím o opravu na __nezbavíme__, protože _zbavit se_ není ani vyjmenované slovo po v, ani slovo s předponou vy-, vý-. Děkuji.

**Comment by ridercz** [comment]
Díky, opraveno.
