### ISSUE TITLE
Zkuste to s drátem: USB tethering na Androidu

### ISSUE THREAD

**Issue by DreitTheDragon** [ridercz/Blog#22]
https://www.altair.blog/2020/08/usb-tethering

Poslušně hlásím, že USB tethering rozhodně je i na Androidu 4.4 (Nastavení -> sdílení připojení) a jednou za čas ho využívám, nejspíš to bude i na starších. Je to trochu schovaný oproti novějším verzím, třeba v nabídce co jde rozkliknout po připojení USB kabelu to není:

![Screenshot_2020-08-15-20-48-35](https://user-images.githubusercontent.com/1199166/90319482-e583bc80-df38-11ea-9fda-d1fb1bad68ff.png)

Nastavení -> sdílení připojení
![Screenshot_2020-08-15-20-48-48](https://user-images.githubusercontent.com/1199166/90319484-e87ead00-df38-11ea-8875-426a93c52f7c.png)

Ještě bych doplnil, že v Linuxu to funguje krásně, objeví se síťovka usb0 a od ní stačí přes DHCP získat adresu :)

**Comment by ridercz** [comment]
Pokud vím, na starších verzích se to lišilo podle výrobce. V každém případě už to není aktuální.
