### ISSUE TITLE
Zvu vás na druhý běh IoT workshopu pro .NET programátory

### ISSUE THREAD

**Issue by pikopage** [ridercz/Blog#41]
https://www.altair.blog/2024/10/iot-workshop
Mapa ukazuje na budovu Microsoftu Vyskočilova 1561/4a, 14000 Prague 4 - Michle, Czechia, ne na Gopas.

**Comment by ridercz** [comment]
Díky za upozornění, ono se to historicky mělo konat v MS a zůstalo to tam.
