### ISSUE TITLE
Úředně bezdomovcem: Trvalé bydliště, proč ho mít a proč ne

### ISSUE THREAD

**Issue by xtonda** [ridercz/Blog#6]
https://www.altair.blog/2011/11/uredne-bezdomovcem-trvale-bydliste-proc-ho-mit-a-proc-ne
Na předchozí verzi webu byla pod článkem rozsáhlá diskuse, kde bylo mnoho doplňujících informací a zkušeností. Je možné to někde dohledat případně znovu zveřejnit?

**Comment by ridercz** [comment]
Ne.
