### ISSUE TITLE
Novoročenka a vánoční soutěž

### ISSUE THREAD

**Issue by jechtom** [ridercz/Blog#7]
Against_stupidity_even_the_gods_themselves_contend_in_vain.
Čerňoučký kůň vymýšlí ďábelské nápady.
The_difference_between_science_and_the_fuzzy_subjects_is_that_science_requires_reasoning,_while_the_other_subjects_require_scholarship.

**Comment by jakubboucek** [comment]
Néééé, tři hodiny se s tím lámu... a ty @jechtom mi v cílové rovince zkazíš prvenství! :-D

**Comment by ridercz** [comment]
Máš samozřejmě pravdu. Nechceš někde zveřejnit kód, kterým jsi to prolomil, abych na něj mohl odkázat?
