### ISSUE TITLE
Noční starosta: bez kvalifikace, bez pravomocí, zato se střetem zájmů

### ISSUE THREAD

**Issue by aidik** [ridercz/Blog#9]
https://www.altair.blog/2019/03/nocni-starosta

Tohle bude `issue` spíše semantického charakteru, protže mi níže uvedená citace přijde významově nekonzistentní:

> … Hana Třeštíková, nechvalně proslulá svým působením v obdobné funkci na Praze 7, kdy zavedla díru na peníze jménem projekt Art District 7 

potud je vše v pořádku, ale následuje:

> a úspěšně napomáhá gentrifikaci čtvrti.

Gentrifikaci vnímám jako něco pozitivního a zároveň jako něco, co se děje spíše nazvdory mnoha krokům sdružení P7S. Proto mi přiznání zásluh nejde dohromady s nechvalnou proslulostí.

**Comment by ridercz** [comment]
Formulace je napsána tak, jak byla zamýšlena.
